image:
  file: .gitpod.Dockerfile

tasks:
  - name: Aufgabe 7
    command: javac Main.java && java Main
  - name: Javadoc
    command: javadoc -d doc Main.java
  - name: Javadoc Server
    command: |
      cd doc
      python3 -m http.server 3000

vscode:
  extensions:
    - vscjava.vscode-java-pack
